# Generated by Django 3.1.4 on 2021-06-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserComponent', '0002_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
