# Generated by Django 3.2.2 on 2021-05-24 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FileComponent', '0002_auto_20210427_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadocument',
            name='DocumentStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datadocument',
            name='SesssionId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datadocument',
            name='DataDocumentType',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumOfFile', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=False)),
                ('SessionUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
