# Generated by Django 3.1.4 on 2021-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileComponent', '0002_auto_20210526_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsession',
            name='SessionName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
