# Generated by Django 3.2.2 on 2021-05-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FileComponent', '0003_auto_20210524_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataDocumentReport', models.TextField(max_length=700)),
                ('DataDocumentJson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileComponent.datadocument')),
            ],
        ),
    ]
