# Generated by Django 3.1.4 on 2021-06-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileComponent', '0003_documentsession_sessionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsession',
            name='SessionType',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
