# Generated by Django 3.1.4 on 2021-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileComponent', '0004_documentsession_sessiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsession',
            name='ChildReport',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentsession',
            name='Status',
            field=models.CharField(default='Loading', max_length=20),
        ),
    ]
