# Generated by Django 3.1.4 on 2021-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileComponent', '0002_datadocumentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadocument',
            name='DataDocumentName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datadocumentcontent',
            name='DataDocumentSentence',
            field=models.CharField(max_length=500),
        ),
    ]
