# Generated by Django 3.1.4 on 2021-03-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id',models.AutoField(primary_key=True)),
                ('username', models.CharField(default='', max_length=30,  serialize=False)),
                ('password', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=30)),
                ('EmailOrganization', models.CharField(blank=True, default='', max_length=30)),
                ('DateOfBirth', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
